### ISSUE TITLE
Training cost

### ISSUE THREAD

**Issue by VividLe** [KMnP/intentonomy#3]
1. Training cost. Using a single NVIDIA V100 GPU, how long can you finish the training process?

2. Do you plan to release the hashtags along with each image?

**Comment by KMnP** [comment]
Thanks for your questions.

1. The full model (img + hs + loc) took us around 19.28 hour with average 8.57 s/batch, img+loc model has similar training time as the full model. The image baseline model took us around 4.29 hour with average 1.95s / batch. Note that we used a batch size of 128 for all our training processes.

2. Unfortunately currently we do not have the plan to release the hashtags since we don't have the permission to release them. I encourage you to check out the metadata provided by unsplash, like keywords.

Hope this information helps!
